### ISSUE TITLE
Change a link

### ISSUE THREAD

**Issue by StephenIsTaken** [3000IQPlay/client-library#10]
Can you like change B+++ github link to the new one? We renamed it from B4 to b+++ because Kopamed said so xd
Also thanks for adding our client

**Comment by StephenIsTaken** [comment]
Change it to this:
https://github.com/StephenIsTaken/Raven-BPlusPlusPlus

**Comment by 3000IQPlay** [comment]
Aight lol

**Comment by 3000IQPlay** [comment]
Tbf the link still would have worked but yeah i get what the point was 👍 (Fixed)
